### ISSUE TITLE
 Otimizar a imagem do background

### ISSUE THREAD

**Issue by ViniciusmDias** [devPitsa/site#21]
A imagem de background está sendo carregada diretamente no css, diminuindo a velocidade de carregamento da página.
Deve ser análisado as melhores opções para carregar a imagem.

**Comment by jbastosufsc** [comment]
Tamanho da imagem otimizado com TinyPNG;

Alternativa para resolução:

Instalar plugin: gatsby-background-image
Referência: https://www.gatsbyjs.org/packages/gatsby-background-image/

**Comment by jbastosufsc** [comment]
Implementado o gatsby-background-image

Passos realizados:

1- yard add gatsby-background-image
2- No arquivo que deverá ser implementado o background: 
 import BackgroundImage from "gatsby-background-image"
 import { graphql, useStaticQuery } from "gatsby"
3-   Criar a tack do BackgroundImage:
<BackgroundImage
        fluid={desktop.desktop.childImageSharp.fluid}
        className="backgroundImg"> 
</ BackgroundImage> 

4-  Criar query no graphql:

query {
        desktop: file(relativePath: { eq: "banner-home.png" }) {
          childImageSharp {
            fluid(quality: 100, maxWidth: 1280) {
              ...GatsbyImageSharpFluid
            }
          }
        }
      }

5- Adicionar CSS a classe do BackgroundImage
