### ISSUE TITLE
Implementar e verificar o funcionamento do formulário de contato

### ISSUE THREAD

**Issue by jbastosufsc** [devPitsa/site#56]

**Comment by ViniciusmDias** [comment]
Descrever as tarefas necessárias para uma futura implementação*

**Comment by jbastosufsc** [comment]
Basically: 

1 - insert this attributes in <form> tag:
        data-netlify="true"
        data-netlify-honeypot="bot-field"

2 - Insert this 2 tags with all the attributes describes below:

            <input type="hidden" name="form-name" value="contact" />

            <div hidden>
              <label>
                Don’t fill this out: <input name="bot-field" />
              </label>
            </div>

More info: https://community.netlify.com/t/common-issue-form-problems-form-debugging-404-when-submitting/92

3 - Go to https://app.netlify.com/ and verify in Forms section of the project if the forms is working.

4 - Create a form notification by e-mail, selecting your current e-mail.
